### PR TITLE
Front end

### PR DESCRIPTION
**Pull request by DuyDao-Dev**
Able to add items to cart using button. From here there's a checkout button which takes you to payment and shipping. Several TODO comments for API request. Please read comments for instructions.

### CODE REVIEW

**Review by linhwatson — CHANGES_REQUESTED** [review]
Hey Duy, please approve my PR (PR #10 ) first since it's our latest working version of the app. The Front End is fully connected to the Back End. Since you are using mock data in your component, please resolve any merge conflicts after you merge my branch to the original repo and pull. Let me know if you have questions/ concerns 👍

**Comment by DuyDao-Dev** [comment]
> Hey Duy, please approve my PR (PR #10 ) first since it's our latest working version of the app. The Front End is fully connected to the Back End. Since you are using mock data in your component, please resolve any merge conflicts after you merge my branch to the original repo and pull. Let me know if you have questions/ concerns 👍

I've approved and merged your PR. Can you check my PR or maybe hop on a call for a little bit to go over the conflicts? I don't want to accidentally delete or overwrite any of your work.

**Comment by linhwatson** [comment]
I'm checking out the conflicts, will update you once I'm done!

**Comment by linhwatson** [comment]
I have resolved all the conflicts. See if it works!

**Comment by DuyDao-Dev** [comment]
> I have resolved all the conflicts. See if it works! 

Sounds good. I'll run it now. We're you able to run it on your machine?

**Comment by linhwatson** [comment]
I'm working on some css, so haven't pulled yet!

**Comment by DuyDao-Dev** [comment]
I'll be home in a bit if you want to connect and work on it together.

**Comment by DuyDao-Dev** [comment]
> I'm working on some css, so haven't pulled yet!

Want to connect and finish off this project? I don't think we'll get it completed since nobody else but you and I logged on this weekend. Hop on Teams if to see my messages.

**Review by linhwatson — APPROVED** [review]

**Pull request merged**
